"""empty message

Revision ID: 0c2368a03611
Revises: 89bef5dde341
Create Date: 2020-11-01 11:07:46.588586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2368a03611'
down_revision = '89bef5dde341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('path', sa.Text(), nullable=True))
    op.create_index(op.f('ix_comment_path'), 'comment', ['path'], unique=False)
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_path'), table_name='comment')
    op.drop_column('comment', 'path')
    op.drop_column('comment', 'parent_id')
    # ### end Alembic commands ###
