"""Identifier column

Revision ID: 0cca9c6154b8
Revises: 7c083370018b
Create Date: 2020-11-19 11:22:22.201952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cca9c6154b8'
down_revision = '7c083370018b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('identifier', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'identifier')
    # ### end Alembic commands ###
