"""Comment identifier

Revision ID: 4493e5c889c2
Revises: bbaea238cc0e
Create Date: 2020-11-19 12:16:32.131271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4493e5c889c2'
down_revision = 'bbaea238cc0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('identifier', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'identifier')
    # ### end Alembic commands ###
